---
- name: Test Playbook to ping inventory hosts
  hosts: server52
  tasks:
    - name: Test ping
      ansible.builtin.ping:
      register: result

    - name: Print ping result
      ansible.builtin.debug:
        msg: "{{ result }}"
